[tool.poetry]
name = "backend"
version = "0.1.0"
description = ""
authors = ["Lars Musters <lars.musters@ictu.nl>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pytexturepacker = "^1.2.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
